# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do
    build_app(scheme: "BK Mortgage",
            workspace: "BK Mortgage.xcworkspace",
            include_bitcode: true,
            export_method: "app-store",
            export_options: {
              provisioningProfiles: { 
                "place_real_estate_dis" => "place_real_estate_dis"
              }
    })
  end

  lane :upload do
    increment_build_number(
      build_number: app_store_build_number + 1,
      xcodeproj: "BK Mortgage.xcodeproj"
    )
    upload_to_app_store(
      submit_for_review: false,
      automatic_release: true,
      force: true,
      run_precheck_before_submit: true,
      skip_screenshots: true,
    )
  end

end
